name: Spell Checker
description: Annotates the build with a file spell check
author: https://github.com/Syin-Max
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false
